### ISSUE TITLE
Too many arguments / Unexpected keyword argument errors with `mypy --strict`

### ISSUE THREAD

**Issue by HonzaRepresent** [samuelcolvin/pydantic#781]
# Bug

Please complete:
* OS: **MacOS 10.14.6**
* Python version: **3.7.4 (default, Jul  9 2019, 18:13:23)
[Clang 10.0.1 (clang-1001.0.46.4)]**
* Pydantic version: **0.32.2**

The issue is similar to #280, but that seems to have been fixed and a part of version 0.32.2 that I've used. I also believe the cause is different.

My MWE:
```py
from pydantic.dataclasses import dataclass

@dataclass(frozen=True)
class Person:
    name: str

Person(name="Bob")
```
When I type-check it with `mypy main.py`, it runs without errors, as expected. However, when I run it with `mypy --strict main.py` (or, more specifically, `mypy --no-implicit-reexport main.py`), I get 

```
error: Module 'pydantic.dataclasses' has no attribute 'dataclass'; maybe "dataclasses"?
error: Unexpected keyword argument "name" for "Person"
```
(or, similarly, for `Person("Bob")`, I get `error: Too many arguments for "Person"`)

> `--no-implicit-reexport` By default, imported values to a module are treated as exported and mypy allows other modules to import them. This flag changes the behavior to not re-export unless the item is imported using from-as or is included in `__all__`. Note this is always treated as enabled for stub files.
(https://buildmedia.readthedocs.org/media/pdf/mypy/latest/mypy.pdf, p.122)

This would lead me to believe that there's an issue with my or pydantic's imports, but it is just a theory.

For now, I hope to work around this by calling mypy without `--no-implicit-reexport`, but I suspect other people will get there when using `mypy --strict`. In general, I'd be happy to know if there's a solution to this. Thanks!

**Comment by samuelcolvin** [comment]
See https://github.com/python/mypy/issues/6239, and see here:

https://github.com/samuelcolvin/pydantic/blob/5015a7e48bc869adf99b78eb38075951549e9ea7/pydantic/dataclasses.py#L100-L101

To get all mypy's dataclass specific goodness we try to fool mypy into thinking `pydantic.dataclasses.dataclass` is just a re-export of the vanilla dataclass.

It might be possible to fool it with something like:

```py
import dataclasses
dataclass = dataclasses.dataclasses
```

If this works, the solution is is simple and I'll accept a PR to fix that. If for some reason that doesn't work, you'd need to ask the mypy people how to proceed.

The other solution is to extend the nascent pydantic mypy plugin to work with pydantic dataclasses #722?

**Comment by HonzaRepresent** [comment]
Thanks for the reply and explanation. I think that beyond perhaps adding this into the docs, I'm out of my depth here. Might create a PR for that in the coming weeks.

**Comment by samuelcolvin** [comment]
should be fixed in #783 which I'll finish tomorrow, if you need this urgently it could be based off v0.32.x and released as a patch?

**Comment by samuelcolvin** [comment]
The other option is to just use

```py
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass

@dataclass(frozen=True)
class Person:
    name: str

Person(name='Bob')
```

Until pydantic v1 is released.

**Comment by HonzaRepresent** [comment]
Samuel, thanks for following through on this. I can wait for that for a bit, especially since I have the liberty to just turn that one mypy check off. 

If that's something you wanted, I could also verify that #783 fixes my issues once its done.

**Comment by morrishopkins** [comment]
I see that this was closed but I am still seeing this issue as well. I am on pydantic 1.6.1
