### ISSUE TITLE
Type field always assigns a default value

### ISSUE THREAD

**Issue by koxudaxi** [samuelcolvin/pydantic#878]
# Bug

* OS: **Ubuntu 18.04**
* Python version:  **3.7.3 (default, Apr  3 2019, 19:16:38)  [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]**

* Pydantic version : **1.0b2**   

I set `Type` on a field as a type annotation which is a subclass of BaseModel.
It works fine without a default value.
However, If I add a default value on the field then, Model always assigns a default value.

```py
from typing import Type

from pydantic import BaseModel, version


class Parent(BaseModel):
    def echo(self):
        print('parent')


class Child(Parent):
    def echo(self):
        print('child')


class Model(BaseModel):
    v: Type[Parent]

Model(v=Parent).v().echo() 
# > parent
Model(v=Child).v().echo()  
# > child

class ModelDefault(BaseModel):
    v: Type[Parent] = Parent

ModelDefault(v=Parent).v().echo()
# parent
ModelDefault(v=Child).v().echo()
# parent <-- expect child

# The Model always assigns a default value

```

**Comment by samuelcolvin** [comment]
Interesting. 

Questions:
* what happens if you use a completely different class eg. `ModelDefault(v=Different).v().echo()`?
* does `Parent` need to inherit from `BaseModel` to cause this problem?

**Comment by koxudaxi** [comment]
OK, I have tried in other cases. It is the same results.

```python
class Different(BaseModel):
    def echo(self):
        print('different')

ModelDefault(v=Different).v().echo()
# > parent

class PythonClass:
    def echo(self):
        print('python_class')

class ModelDefaultPythonClass(BaseModel):
    v: Type[PythonClass] = PythonClass

ModelDefaultPythonClass(v=Child).v().echo()
# > python_class
ModelDefaultPythonClass(v=str).v().echo()
# > python_class
```

Also, I look that `__fields__` is empty.
```
print(Model.__fields__)
{'v': <ModelField(v type=typing.Type[__main__.Parent] required)>}

print(ModelDefault.__fields__)
# > {}

print(ModelDefaultPythonClass.__fields__)
# > {}
```

I found the reason, It's in `ModelMetaclass `.
https://github.com/samuelcolvin/pydantic/blob/6a0e5313cb60792f17dda103b7e2bf45246a1060/pydantic/main.py#L178-L179

If We set `type` as default value on a field then, the condition is `True` because `type` is in `untouched_types` .

What do you think about this problem?

**Comment by samuelcolvin** [comment]
> What do you think about this problem?

I think we should fix it asap, before v1.

I guess it should be something like

```py
if isinstance(value, untouched_types) and ann_type != PyObject and lenient_issubclass(getattr(ann_type, '__origin__', None), Type): 
    continue
```

(Just a guess)

Would you like to submit a PR, or should I?

**Comment by koxudaxi** [comment]
OK, I can create the PR.

**Comment by koxudaxi** [comment]
> I think we should fix it asap, before v1.

I have created this PR from the master branch.
because of the large difference from master and v0.32.x

If you would fork from v0.32.x then, I recreate the PR from v0.32.x.

**Comment by oleksii-symon-corva-ai** [comment]
Hi! I think, that the issue still exists.

```python3
from pydantic import BaseModel
from typing import Type


class BaseEvent:
    pass


class ConcreteEvent(BaseEvent):
    pass


class BaseClass(BaseModel):
    event_cls: Type[BaseEvent]


class ChildClass(BaseClass):
    event_cls = ConcreteEvent


ChildClass()

# > ValidationError: 1 validation error for ChildClass
# >  event_cls
# >  field required (type=value_error.missing)
```


System information:

```python3
from pydantic.version import version_info

print(version_info())

# > pydantic version: 1.7.3
# > pydantic compiled: True
# > install path: /home/oleksii/miniconda3/envs/3.8/lib/python3.8/site-packages/pydantic
# > python version: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0]
# > platform: Linux-5.4.0-58-generic-x86_64-with-glibc2.10
# > optional deps. installed: []
```

**Comment by PrettyWood** [comment]
Hi @oleksii-symon-corva-ai 
Your issue is something else. It's because of https://github.com/samuelcolvin/pydantic/issues/782
If you write something like
```python
class BaseClass(BaseModel):
    x: Union[int, float]

class ChildClass(BaseClass):
    x = 3

ChildClass()
```
It will fail because it will infer type `int` and compare it with `Union[int, float]` and fail.
It's the same for you so you need to repeat the type information 
```python
class ChildClass(BaseClass):
    event_cls: Type[BaseEvent] = ConcreteEvent
```
We can discuss this matter further on the linked issue.
Hope it helps!
